import { PUBLIC_CATEGORY_LABELS } from './publicLabels'

export const DEMO_PROFILE_02 = {
  id: 'demo_profile_02',
  calendar: {
    startServiceDay: 331,
    daysPerMonth: 30,
    monthsPerYear: 12,
    dayDurationMsAtOneX: 24_000,
  },
  resources: {
    companyCapacityPerCategory: 18,
    startingCompanyBlocksPerCategory: 16,
    monthlyCompanyBlocksMinimum: 1,
    monthlyCompanyBlocksMaximum: 4,
    legacyReserveCapacity: 18,
    legacyStartingReserveResources: 3,
    diversionSuspicion: 2.4,
    normalContribution: 1,
    disguisedContribution: 0.5,
    compressedNormalContribution: 1.05,
    compressedDisguisedContribution: 0.525,
    disguiseRecoveryDays: 30,
  },
  player: {
    startingSuspicion: 0,
    startingReputation: 60,
    startingMarketShare: 58,
  },
  evaluation: {
    expectedBase: 12.6,
    expectedGain: 4.14,
    expectedDecayMonths: 26,
    reputationPassGain: 1,
    reputationFailurePerCategory: 2,
    severeDeficitThreshold: 2,
    severeDeficitPenalty: 1,
    consecutiveFailuresPerDisposal: 2,
    commercialShareThreshold: 8,
    commercialReputationThreshold: 20,
    commercialFailureMonthsPerDisposal: 3,
    maximumDisposalStage: 3,
  },
  suspicion: {
    naturalDailyDecrease: 0.037,
    auditFailureIncrease: 25,
  },
  audit: {
    baseProbability: 0.03,
    suspicionProbabilityGain: 0.45,
    suspicionExponent: 1.7,
    maximumProbability: 0.48,
  },
  bombs: {
    firstEligibleServiceDay: 361,
    warningSuspicion: 40,
    highSuspicion: 70,
    mediumIntervalDays: 6 * 30,
    highIntervalDays: 3 * 30,
    maximumPerCategory: 1,
    maximumTotal: 3,
    triggerSuspicionIncrease: 15,
    failedExplanationSuspicionIncrease: 20,
    repeatedExplanationPenalty: 0.15,
  },
  competitors: {
    meridian: {
      name: 'MERIDIAN',
      startingMarketShare: 36,
      serviceScore: 82,
      reputation: 62,
      recoveryRate: 0.42,
      dailyRecoveryFactor: 0.08,
    },
    tallow: {
      name: 'TALLOW',
      startingMarketShare: 6,
      serviceScore: 76,
      reputation: 54,
      recoveryRate: 0.27,
      launchDelayDays: 7 * 30,
      launchAvailability: 0.55,
      dailyAvailabilityGrowth: 0.01,
      dailyScoreGrowth: 0.08,
      volatilityStep: 0.65,
      volatilityCycleDays: 9,
    },
  },
} as const

export const CATEGORY_LABELS = PUBLIC_CATEGORY_LABELS
